### ISSUE TITLE
get error in docker when executing ./generate

### ISSUE THREAD

**Issue by bahmansh** [cyberman219/cloudflare-vpn-for-desktop#6]
=====wgcf-profile.conf=====
cat: can't open 'configs/wgcf-profile.conf': No such file or directory

=====wgcf-identity.json=====
cat: can't open 'configs/wgcf-identity.json': No such file or directory

**Comment by holao09** [comment]
I've get this errors too.
May Cloudflare change API ?

**Comment by cyberman219** [comment]
> =====wgcf-profile.conf=====
> cat: can't open 'configs/wgcf-profile.conf': No such file or directory
> 
> =====wgcf-identity.json=====
> cat: can't open 'configs/wgcf-identity.json': No such file or directory

It seems Cloudflare changed their APIs.

**Comment by cyberman219** [comment]
Updated new instruction
